### ISSUE TITLE
Docs archive

### ISSUE THREAD

**Issue by joerg** [chef/chef-web-docs#1492] opened 2018-07-09 14:40 UTC
Although the docs archive is still linked on the main page https://docs.chef.io/ it seems to be completely unmaintained. The last archived version is from Oct 2016 (https://docs-archive.chef.io/) of chef version 12.13. This also means that there are no archived docs of version 13 at all.
Is the docs archived still maintained or has anything changed about this? The reason I came up with this is because http://devdocs.io scrapes these archives and builds a nice searchable index but since only version 12 is available in the archive devdocs has become a bit outdated lately.

regards,
    Jörg

**Comment by IanMadd** [comment] 2022-06-03 15:27
Closing as it's a duplicate of #3610

**Closed as completed by IanMadd** 2022-06-03 15:27 UTC
Labels: Aspect: Documentation, Type: Docs Debt
