### ISSUE TITLE
"Chef Workstation Release Notes" search returns nothing useful

### ISSUE THREAD

**Issue by tas50** [chef/chef-web-docs#2926] opened 2021-02-08 15:31 UTC
### User Story
As a sysadmin, I will use this work when I want to find the release notes for the latest version of Workstation.

## Description
It looks like due to the title of the Workstation release note page it doesn't show up in search like the other pages that start with `Release Notes:`

**Comment by IanMadd** [comment] 2021-02-09 19:07
Seems that the issue is that the seamless release notes pages don't have the term "Release Notes" anywhere in the Hugo generated text so Swiftype would never add those pages to a "release notes" index.

**Comment by tas50** [comment] 2021-02-09 20:02
Yeah I think just adding the text to the page would do it.

**Comment by IanMadd** [comment] 2021-02-10 00:17
This should be fixed with #2930
We'll have to wait for Swiftype to update the site index to find out.

**Closed as completed by IanMadd** 2021-02-10 00:17 UTC
